# Generated by Django 5.2.4 on 2025-08-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_details', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('weight_kg', models.FloatField()),
                ('height_cm', models.FloatField()),
                ('activity_level', models.CharField(help_text='e.g., Sedentary, Lightly Active', max_length=50)),
                ('dietary_preferences', models.CharField(help_text='e.g., Vegan, Non-Veg', max_length=200)),
                ('allergies', models.TextField(blank=True, help_text='Comma-separated list of allergies')),
                ('health_issues', models.TextField(blank=True, help_text='e.g., Diabetes, High Blood Pressure')),
            ],
        ),
    ]
