# Generated by Django 5.2.4 on 2025-08-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dosage', models.CharField(help_text='e.g., 500mg', max_length=50)),
                ('inventory', models.PositiveIntegerField(default=0, help_text='e.g., number of pills')),
                ('refill_threshold', models.PositiveIntegerField(default=10, help_text='Notify when inventory falls below this')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_notified', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
