# Generated by Django 5.2.4 on 2025-08-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_agent', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='instruction',
            field=models.CharField(choices=[('Before Food', 'Before Food'), ('After Food', 'After Food'), ('With Food', 'With Food'), ('Any Time', 'Any Time')], default='Any Time', max_length=20),
        ),
        migrations.AddField(
            model_name='reminder',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
